
default:
	#arm-himix200-linux-gcc -o libcurl_client ./libcurl_client.cpp -I /home/aperol/workspace/White-USBnIP-Int/trunk/plcm-white/thirdparty/curl/dist/linux_3519A/include -L /home/aperol/workspace/White-USBnIP-Int/trunk/plcm-white/thirdparty/curl/dist/linux_3519A/lib/ -lcurl -L /home/aperol/workspace/White-USBnIP-Int/trunk/plcm-white/thirdparty/openssl_1_0_0/ssl/lib/ -lssl -lcrypto
	gcc -o openssl_server ./openssl_server.cpp -I /home/aperol/Software_tmp/openssl_build/ssl/include/ -L /home/aperol/Software_tmp/openssl_build/ssl/lib/ -lssl -lcrypto